resources:
  - name: avishayh_dbp_repo
    type: GitRepo
    configuration:
      gitProvider: avishayh_github                   
      path: avishayh/jfrog-pipelines-docker-sample    
      branches:
        include: master

  - name: avishayh_dbp_image
    type: Image
    configuration:
      registry: art_v                                
      sourceRepository: docker_local               
      imageName: avishayhtest.jfrog.info/docker-local/dbp  # < -- replace with your image path and name
      imageTag: latest
      autoPull: true
      
  - name: avishayh_dbp_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildName: dbp_build
      buildNumber: 1    

  - name: avishayh_dbp_promoted_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildName: dbp_build
      buildNumber: 1
      

pipelines:
  - name: avishayh_pipeline_dbp
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: dbp_group
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: avishayhtest.jfrog.info/docker-local/dbp  # replace with your image path and name
          dockerImageTag: ${run_number}
          inputResources:
            - name: avishayh_dbp_repo
          integrations:
            - name: art_v                            # <-- replace with your artifactory integration

      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: dbp_group
          targetRepository: docker-local
          integrations:
            - name: art_v                            # <-- replace with your artifactory integration
          inputSteps:
            - name: docker_build
          outputResources:
            - name: avishayh_dbp_image

      - name: publish_dbp_build
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push
          outputResources:
            - name: avishayh_dbp_build_info

      - name: promote_dbp_build
        type: PromoteBuild
        configuration:
          targetRepository: demo-pipelines
          integrations:
            - name: art_v
          inputResources:
            - name: avishayh_dbp_build_info
          outputResources:
            - name: avishayh_dbp_promoted_build_info

